### ISSUE TITLE
question

### ISSUE THREAD

**Issue by anentropic** [zuloo/esniper#1]
Hi,

Just wondering is this a fork of http://sourceforge.net/projects/esniper ?

I'm currently looking for an alternative more actively developed that can give a bit more info about what went wrong when it failed.  I'd love to get more hands on with it myself but C is not a language I've ever worked with before.

Are you using this code successfully on auctions at the moment?

thanks

**Comment by zuloo** [comment]
Hi, 

yes it is a (inofficial) fork of http://sourceforge.net/projects/esniper .

I was looking for a working sniper that can be hosted on my own intranet-server when I found some php-frontends that used esniper as their backend. Unfortunately these frontends did not work for me, but the esniper version from the developers CSV did work quite ok.

It had some problems displaying the watchlist and in general displaying special language chars - I think ebay did some frontend-polishing and switched to UTF-8, which accounted for these bugs. I also found an other bug, which kept esniper from destinguishing between won and lost auctions.

after debugging the code I took the more or less very basic frontend, that could be found in the CSV-sources as well, and gave it facelift. The result is snyp ( https://github.com/zuloo/snyp ), which now works as desired. Compiling esniper is very easy, because it only depends on curl and som standart c-libraries. I run it under debian wheezy and it seems to be very reliable - for me it did 10 succesful snipes out of 10.

I have to confess that my c and c++ skills did not get much attention the last years, and I thought about a rewrite in python, but I am also lazy and dont like to create clones of otherwise good working software - so I gave it a try and it worked out pretty well.

So far you can see if your bet was too low in the end. Snyp also keeps track of the running esniper processes and restarts them if they die for some reason).

Best regards
Jan

**Comment by zuloo** [comment]
Just updated the UTF-8 handling, as it caused errors in parsing the bid-history recently. you should update if you use this code.
